name: xpression_collector
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.12.7
  
  # Python libraries
  - pandas
  - matplotlib
  - pyfiglet #optional
  - rich #optional
  
  # External tools
  - kallisto=0.52.0
  - busco=6.1.0
  - sra-tools=3.4.1
  - kingfisher=0.5.0

